package com.cloud.plug_in_sales.model;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gid
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.pwd
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gid
     *
     * @return the value of goods.gid
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gid
     *
     * @param gid the value for goods.gid
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.pwd
     *
     * @return the value of goods.pwd
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.pwd
     *
     * @param pwd the value for goods.pwd
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status
     *
     * @return the value of goods.status
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status
     *
     * @param status the value for goods.status
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}