#springboot项目配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sale?serverTimezone=GMT%2B8&amp
    username: root
    password: naonao
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  thymeleaf:
    cache: false
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.cloud.plug_in_sales.mapper
  mapper-locations: classpath:mapper/*.xml
#日志配置
logging:
  file: logs/sale.log
#服务器配置
server:
  servlet:
    session:
      timeout: 15552000
  port: 8080
