package com.cloud.plug_in_sales.mapper;

import com.cloud.plug_in_sales.model.Goods;
import com.cloud.plug_in_sales.model.GoodsExample;
import java.util.List;

import com.cloud.plug_in_sales.model.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.web.bind.annotation.PathVariable;

/**
 * @author 张玉雷
 */
@Mapper
public interface GoodsMapper {
    /**
     * @param newUser 当前传过来的用户
     * @param oldUser 数据库已经存在的用户
     */
    void updateUser(@Param("newUser") User newUser, @Param("oldUser") User oldUser);

    User selectUserByQQ(@Param("user") User user);
    /**
     * @return 获取可用的密钥数量
     */
    int getStock();
    /**
     * @param user 保存用户
     */
    void saveUser(@Param("user") User user);
    /**
     * @param count 密钥数量
     * @return 指定符合要求的密钥值
     */
    List<String> getPwdByCount(@Param("count") int count);

    /**
     * @param pwd 密钥
     *            根据密钥修改状态
     */
    void updateStatusByPwd(@Param("pwd") String pwd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    long countByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    int deleteByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    int deleteByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    List<Goods> selectByExampleWithRowbounds(GoodsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    List<Goods> selectByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    Goods selectByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    int updateByExample(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Mar 15 10:21:59 CST 2020
     */
    int updateByPrimaryKey(Goods record);

}